Improve font lock and indent
mrc/tla-tools pull request #1
Opened 2019-10-18 11:30 UTC by dmilstein

Hello,

First off, thanks very much for creating this emacs mode! I've been exploring TLA+ and Pluscal lately, and being able to start with a functioning emacs mode, instead of having to use the Toolbox, has been an absolute godsend.

Second: I've been doing a bunch of hacking on the mode -- adding font-lock coverage for more of the pcal/tla+ features, fixing a bunch of indentation issues, and adding some new indentation support (e.g. to indent inside of parens or braces).

I'm submitting a bunch of (mostly smallish) commits as one big PR. If you'd prefer some other style of collaboration, let me know what's useful to you. I tried to make the individual commit messages fairly clear as to what each was doing (and added a decent chunk of ert tests to make it even clearer).

2019-10-29 03:05 UTC, mrc requested changes
Hi, this is fantastic, thank you!

I see you set the tab width, but I prefer spaces for indentation, so do you mind running `untabify`?

2019-10-29 03:05 UTC, mrc commented on tla-pcal-mode.el
> +    (dotimes (n (length lines))
Nice change, thanks!

2019-10-29 03:05 UTC, mrc commented on test/tla-pcal-mode-test.el
> +;;; tla-pcal-mode-test.el --- testing for TLA and PlusCal modes -*- lexical-binding: t; -*-
Thanks!

2019-10-29 03:10 UTC, mrc commented
To answer your comments: I really do like this style, reviewing each commit was helpful for me, and I appreciate your commit messages which show each change is thoughtful. The only sticking point I have is the tabs, do you mind removing them?

About the tests: I've been thinking it would be better if the tests were in example files which could be read in and the indent width inferred for each line, rather than explicit. It would make it easier to drop in new and more complex files (I was working through "Practical TLA+" and making the tests more complex as I got through more of the book.) The explicit line-by-line tests came from an early approach I took when I had only a few simple test cases, but as it grew it became a bit unwieldily.

Seeing as you're contributing to this and adding tests, I figure you might have some good ideas here, so let me know what you think.

2019-10-29 16:41 UTC, dmilstein commented
Got rid of the tabs (I am strongly with you, and am very happy to move to spaces).

Example files for tests: I love this idea. I'm hoping I'll have time to do a bit more hacking, and will see if I can implement this as/when I get into that (to be clear: I am leveling up on elisp in order to do all this, so I'm not, like, an expert ;-)

2019-11-03 01:26 UTC, mrc commented
Thank you!!

2019-11-03 01:27 UTC, merged